name: manual-test

on: 
  workflow_dispatch:
    inputs:
      package:
        description: 'Select package to test'
        required: true
        default: 'warning'
        type: choice
        options:
          - Edge
          - Seller
          - All

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test log
        run: echo Test is running
      - name: Selected Package
        run: echo Selected package is -> ${{ inputs.package }}


