name: Jest Coverage

on:
  push:
    branches:
      - main

jobs:
  jest-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests with Coverage
        run: npm test -- --coverage

      - name: Deploy Coverage Report
        run: npm run deploy

      - name: Archive Coverage Reports
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage
