name: Run unit test case via PR label

on:
  pull_request:
    branches:
      - staging
    types: [labeled]
    paths:
      - 'packages/**'
      - '__tests__/**'
      - '__mocks__/**'
      - 'jest/**'
  

jobs:
  run-tests:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'run test')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      # ------------ Install dependencies----------------
      - name: Install dependencies
        run: npm ci
      # ----------------Run test cases----------------
      - name: Run tests
        run: npm run test:unit